# For CAS Authentication
logoutUrl=http://localhost:7070/cas/logout?service=http://localhost:8080/yourapp
theme.root=http://mks.com.vn/themes/robust-admin/


driverClassName@javax.sql.BaseDataSource=com.mysql.cj.jdbc.Driver
url@javax.sql.BaseDataSource=jdbc:mysql://127.0.0.1:3306/sakai23?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#url@javax.sql.BaseDataSource=jdbc:mariadb://127.0.0.1:3306/xtoeic?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
username@javax.sql.BaseDataSource=sakai_user
password@javax.sql.BaseDataSource=Sakai!123
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

auto.ddl=true
hibernate.show_sql=false
hibernate.hbm2ddl.auto=update
validationQuery@javax.sql.BaseDataSource=select 1 from INFORMATION_SCHEMA.SYSTEM_USERS